---

- name: Debian | ensure apt-transport-https and gpg are present
  ansible.builtin.apt:
    name: [apt-transport-https, gpg]
    state: present

- name: Add falcosecurity key
  ansible.builtin.apt_key:
    url: https://falco.org/repo/falcosecurity-3672BA8F.asc
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Install falcosecurity apt source
  vars:
    pkg_name: "{{ 'deb-dev' if (falco_dev) else 'deb' }}"
  ansible.builtin.apt_repository:
    repo: "deb https://download.falco.org/packages/{{ pkg_name }} stable main"
    filename: falcosecurity
    mode: 0444
    state: present

- name: Debian | kernel headers install
  ansible.builtin.apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
  ignore_errors: true
  register: pkg_result
  until: pkg_result is success

- name: Debian | falco install
  ansible.builtin.apt:
    name: "{{ falco_pkgs }}"
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success
