---

- name: apt | ensure apt-transport-https is present
  apt:
    name: apt-transport-https
    state: present

- name: add draios key
  apt_key:
    url: https://falco.org/repo/falcosecurity-3672BA8F.asc
    state: present
  register: pkg_result
  until: pkg_result is success
- name: install draios apt source
  apt_repository:
    repo: "https://dl.bintray.com/falcosecurity/deb stable main"
    filename: falcosecurity
    mode: 0444
    state: present

## to ensure gcc available for dkms
- include: gcc.yml

- name: apt | kernel headers install
  apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present
  ignore_errors: true
  register: pkg_result
  until: pkg_result is success

- name: apt | falco install
  apt:
    name: "{{ falco_pkgs }}"
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success
