---

- name: Ensure logrotate package is present
  ansible.builtin.package:
    name: logrotate
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Add logrotate configuration for falco log
  ansible.builtin.template:
    src: logrotate-falco.j2
    dest: /etc/logrotate.d/falco
    mode: '0644'
    backup: yes
    validate: 'logrotate -dv %s'
