---

- name: Ensure rsyslog is present
  package:
    name: rsyslog
    state: present
  register: pkg_result
  until: pkg_result is success

- name: get rsyslog version
  shell: "rsyslogd -v | awk 'match($0, /rsyslogd\\s+([0-9.]+)/, a) { print a[1] }'"
  environment:
    PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  changed_when: false
  register: rsyslog_v

- name: Ensure base directory exists
  file:
    dest: "{{ falco_syslog_target | dirname }}"
    state: directory
    mode: '0755'
    owner: "{{ syslog_user }}"
    group: root
  when: >
    "'/var/log/' in falco_syslog_target" and
    falco_syslog_target|dirname != '/var/log'

- name: Check if falco syslog file exists
  stat:
    path: "{{ falco_syslog_target }}"
  register: falcolog

- name: Ensure log file have right permissions
  file:
    dest: "{{ falco_syslog_target }}"
    state: touch
    mode: '0640'
    owner: "{{ syslog_user }}"
    group: root
  when:
    - "'/var/log/' in falco_syslog_target"
    - not falcolog.stat.exists

- name: setup rsyslog to send falco logs to a specific target
  template:
    src: rsyslog-falco.conf.j2
    dest: /etc/rsyslog.d/30-falco.conf
    mode: '0644'
    backup: yes
  notify:
    - restart rsyslog
