---

- block:
    - name: install falco systemd configuration
      template:
        src: "systemd-{{ item }}.service.j2"
        dest: "/lib/systemd/system/{{ item }}.service"
        mode: '0644'
        backup: yes
      with_items:
        - falco
      register: systemdconf
      failed_when: false
      notify:
        - reload systemd
        - restart falco
    - block:
        - import_tasks: immutable.yml
          vars:
            target_dir: /lib/systemd/system
            state: pre
        - import_tasks: immutable.yml
          vars:
            target_dir: /lib/systemd/system/falco.service
            state: pre
        - name: install falco systemd configuration (immutable)
          template:
            src: "systemd-falco.service.j2"
            dest: "/lib/systemd/system/falco.service"
            mode: '0644'
            backup: yes
          notify:
            - reload systemd
            - restart falco
        - import_tasks: immutable.yml
          vars:
            target_dir: /lib/systemd/system
            state: post
        - import_tasks: immutable.yml
          vars:
            target_dir: /lib/systemd/system/falco.service
            state: post
      when: systemdconf is failed
    - block:
        - name: enable and start falco systemd services
          service:
            name: "{{ item }}"
            enabled: yes
            state: 'started'
          failed_when: false
          with_items:
            - falco
      when: falco_service_enabled
    - block:
        - name: disable and stop falco systemd service
          service:
            name: "{{ item }}"
            enabled: no
            state: 'stopped'
          failed_when: false
          with_items:
            - falco
      when: not falco_service_enabled
    - name: Remove init.d script
      file:
        path: /etc/init.d/falco
        state: absent
      register: initd
      failed_when: false
    - block:
        - import_tasks: immutable.yml
          vars:
            target_dir: /etc/init.d/
            state: pre
        - import_tasks: immutable.yml
          vars:
            target_dir: /etc/init.d/falco
            state: pre
        - name: Remove init.d script
          file:
            path: /etc/init.d/falco
            state: absent
        - import_tasks: immutable.yml
          vars:
            target_dir: /etc/init.d
            state: post
      when: initd is failed
  when: ansible_service_mgr == 'systemd'
