---

- name: Systemd
  block:
    - name: Install unit
      block:
        - name: install falco systemd configuration
          ansible.builtin.template:
            src: "systemd-{{ item }}.service.j2"
            dest: "/lib/systemd/system/{{ item }}.service"
            mode: '0644'
            backup: yes
          with_items:
            - falco
          register: systemdconf
          notify:
            - reload systemd
            - restart falco
      rescue:
        - import_tasks: immutable.yml
          vars:
            target_dir: /lib/systemd/system
            state: pre
        - import_tasks: immutable.yml
          vars:
            target_dir: /lib/systemd/system/falco.service
            state: pre
        - name: install falco systemd configuration (immutable)
          ansible.builtin.template:
            src: "systemd-falco.service.j2"
            dest: "/lib/systemd/system/falco.service"
            mode: '0644'
            backup: yes
          notify:
            - reload systemd
            - restart falco
        - import_tasks: immutable.yml
          vars:
            target_dir: /lib/systemd/system
            state: post
        - import_tasks: immutable.yml
          vars:
            target_dir: /lib/systemd/system/falco.service
            state: post
    - name: Service state
      block:
        - name: enable and start falco systemd services
          ansible.builtin.service:
            name: "{{ item }}"
            enabled: yes
            state: 'started'
          failed_when: false
          with_items:
            - falco
      when: falco_service_enabled
    - name: No Service
      block:
        - name: disable and stop falco systemd service
          ansible.builtin.service:
            name: "{{ item }}"
            enabled: no
            state: 'stopped'
          failed_when: false
          with_items:
            - falco
      when: not falco_service_enabled
    - name: Ensure no init.d script
      block:
        - name: Remove init.d script
          ansible.builtin.file:
            path: /etc/init.d/falco
            state: absent
          register: initd
      rescue:
        - import_tasks: immutable.yml
          vars:
            target_dir: /etc/init.d/
            state: pre
        - import_tasks: immutable.yml
          vars:
            target_dir: /etc/init.d/falco
            state: pre
        - name: Remove init.d script
          ansible.builtin.file:
            path: /etc/init.d/falco
            state: absent
        - import_tasks: immutable.yml
          vars:
            target_dir: /etc/init.d
            state: post
  when: ansible_service_mgr == 'systemd'
